# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8082
  servlet:
    context-path: / #gs-generator

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.114.157.44:3306/o_lift?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: duoke8888
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/statics/,classpath:/views/

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
#    type-aliases-package: com.info.moduless


