# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8083
  servlet:
    context-path: #/api

spring:
  thymeleaf:
    prefix: classpath:/templates/
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

renren:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.info.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#云存储
kuaiyun:
  ACCESS_KEY:  ZD37UIX888VBR07BGUFV
  SECRET_KEY:  j1IQ6hOSs62SD1YhuDkQ6/jfVcv35jX2zgJ8l8eI
  RESOURCE:  VG3OQ81wtrNn7lCSdBAwe+gg9rORx+3K
  VOUCHER:  c98d2c31ec9eb25a144899cdda258766


